### PR TITLE
(fix): cache partial decoder

### LINKED ISSUE #90: Reuse partial decoders
[This comment](https://github.com/ilan-gold/zarrs-python/pull/87#discussion_r1959293178) by @flying-sheep  made me realise we are missing a potentially large perf optimisation for `zarrs-python`. We should reuse partial decoders for batches of `chunk_descriptions` that refer to the same chunk in `retrieve_chunks_and_apply_index`.
https://github.com/ilan-gold/zarrs-python/blob/53af191c7ca5215c31221520da1ee1c634852b78/src/lib.rs#L312-L329

The `ChunkRepresentation` can be reused for each batch too.

Relevant: https://book.zarrs.dev/arrays/array_read.html#reading-multiple-chunk-subsets

### PR DESCRIPTION
**Pull request by ilan-gold**
Fixes #90 (hopefully) - I benchmarked and performance (at least relatively speaking) did not go down, but also did not go up, although our benchmarks are probably not really checking for this behavior.

I went with `HashMap` because I couldn't see a reason to use `BTreeMap` (I see it's used elsewhere and that people in rust seem to use it as a drop-in replacement for `HashMap` because it's faster sometimes? Not really familiar with this TBH).

I am also not sure the `key` is the right thing to hash on - the "key" here would be a shard, and we want to share the decoder per shard, right?

### CODE REVIEW

**Comment by LDeakin** [comment]
> the "key" here would be a shard, and we want to share the decoder per shard, right?

Yep! The partial decoder for the sharding codec retrieves and decodes the shard index only once.

However, the partial decoder cache should only live as long as the batch of requests in `retrieve_chunks_and_apply_index`. Otherwise, it would perpetually grow and become stale after subsequent writes. I should document this better, but partial decoder *initialisation* can perform store and codec operations (and may even decode entire chunks with certain codecs!).

- https://docs.rs/zarrs/latest/zarrs/array/struct.Array.html#optimising-reads
- https://book.zarrs.dev/arrays/array_read.html#reading-multiple-chunk-subsets

So my recommendation is to avoid locks and:
1. Identify the unique chunks and create partial decoders for each in parallel.
2. Run `partial_decode_into` in parallel for each chunk subset

**Comment by ilan-gold** [comment]
Separately there seems to be an error about `typesize` which I would guess is somehow related to my work on that https://github.com/zarr-developers/numcodecs/pull/713

**Comment by ilan-gold** [comment]
Yup, https://github.com/zarr-developers/numcodecs/blob/58bc9c4da74e06fbec985d4235f912b31d4d31f6/numcodecs/abc.py#L79-L95 means it is now part of the configuration.  So we can probably ignore it, will open a separate PR

**Comment by ilan-gold** [comment]
Seems like I did 1. by constructing a `HashMap` of the keys that require partial mapped to their `WithSubset` and then parallel-iterate to create tuples that have the key and the decoder before updating the `HashMap` representing the mapping of key to decoder.  2. Should already be handled

File: src/lib.rs [hunk 1]
```diff
@@ -265,15 +271,43 @@ impl CodecPipelineImpl {
...
         };
 
+        // Assemble partial decoders ahead of time and in parallel
+        let mut item_map: HashMap<StoreKey, &WithSubset> = HashMap::new().into();
+        chunk_descriptions
+            .iter()
+            .filter(|item| !(is_whole_chunk(item)))
+            .for_each(|item| {
+                item_map.insert(item.key().clone(), item);
+            });
```
Comment (ilan-gold) [inline src/lib.rs:281]: I think there is a cleaner way to do this...

File: src/lib.rs [hunk 2]
```diff
@@ -308,18 +341,20 @@ impl CodecPipelineImpl {
...
-                        .partial_decoder(input_handle, item.representation(), &codec_options)
-                        .map_py_err::<PyValueError>()?;
+                    let key = item.key();
+                    let partial_decoder: PyResult<&Arc<dyn ArrayPartialDecoderTraits>> =
+                        match partial_decoder_cache.get(key) {
+                            Some(e) => Ok(e),
+                            None => Err(PyRuntimeError::new_err(format!(
+                                "Partial decoder not found for key: {key}"
+                            ))),
+                        };
```
Comment (LDeakin) [inline src/lib.rs:351]:
```suggestion
                    let partial_decoder = partial_decoder_cache.get(key).ok_or_else(|| {
                        PyRuntimeError::new_err(format!("Partial decoder not found for key: {key}"))
                    })?;
```

File: src/lib.rs [hunk 3]
```diff
@@ -308,18 +341,20 @@ impl CodecPipelineImpl {
...
                     unsafe {
                         // SAFETY:
                         // - output is an array with output_shape elements of the item.representation data type,
                         // - item.subset is within the bounds of output_shape.
                         // - item.chunk_subset has the same number of elements as item.subset.
-                        partial_decoder.partial_decode_into(
+                        partial_decoder?.partial_decode_into(
```
Comment (LDeakin) [inline src/lib.rs:357]:
```suggestion
                        partial_decoder.partial_decode_into(
```

File: src/lib.rs [hunk 4]
```diff
@@ -265,15 +272,41 @@ impl CodecPipelineImpl {
...
+                        .clone()
+                        .partial_decoder(
+                            Arc::new(input_handle),
+                            item.representation(),
+                            &codec_options,
+                        )
+                        .map_py_err::<PyValueError>()?;
+                    Ok((item.key().clone(), partial_decoder))
+                })
+                .collect::<PyResult<Vec<_>>>()?;
```
Comment (LDeakin) [inline src/lib.rs:299]:
```suggestion
            let key_decoder_pairs = iter_concurrent_limit!(
                chunk_concurrent_limit,
                partial_chunk_descriptions,
                map,
                |item| {
                    let input_handle = self.stores.decoder(item)?;
                    let partial_decoder = self
                        .codec_chain
                        .clone()
                        .partial_decoder(
                            Arc::new(input_handle),
                            item.representation(),
                            &codec_options,
                        )
                        .map_py_err::<PyValueError>()?;
                    Ok((item.key().clone(), partial_decoder))
                }
            )
            .collect::<PyResult<Vec<_>>>()?;
```

**Review by LDeakin — APPROVED** [review]
Nice! Just a minor nit on `Option -> Result` + ensuring that the chunk concurrent limit is used.
